const childOptionsMap = {
    "Yenidogan": ["YD1", "YD2", "YD3", "YD4", "YD5", "YD6", "YD7", "YD8", "YD9"],
    "Onkoloji": ["Çocukluk Çağı Lösemileri", "Lenfomalar", "Beyin Tümörleri",
        "Nöroblastom", "Wilms & Diğer Böbrek Tümörleri", "Yumuşak Doku Tümörleri",
        "Kemik Tümörleri", "Diğer Maligniteler"],
    "Endokrinoloji": ["Hipofiz & Hipotalamus Hastalıkları", "Püberte & Erken Pübertal Bozukluklar",
        "Tiroid Hastalıkları", "Adrenal Bez Hastalıkları", "Gonad Hastalıkları", "Paratiroid Hastalıkları",
        "Diabetes Mellitus"],
    "Metabolizma": ["Met. Hastalıklara Giriş", "Fenilalanin Met. Hastalıkları", "Tirozin Met. Hastalıkları",
        "Metionin Met. Hastalıkları", "Triptofan Met. Hastalıkları", "Organik Asidemiler",
        "Diğer Aminoasidopatiler", "Hiperamonyemi ve üre siklus defektleri", 
        "Galaktoz, Fruktoz, Laktik Asidozla Seyreden Met. Hastalıkları", "Glukojen Dep Hastalıkları",
        "Mukopolissakkoridozlar", "Yağ asidi Oksidasyon defektleri", "Lipid depo hastalıkları"],
    "Hematoloji": ["Anemilerin Sınıflandırılması", "Hipoplastik Anemiler", "Megaloblastik Anemiler",
        "Mikrositer Anemiler", "Hemolitik Anemiler", "Pansitopeni ve Polistemi",
        "Kanama Bozuklukları ve Tromboz"],
    "Noroloji": ["SSS Konjenital Malformasyonları, Mikrosefali, Makrosefali, Kraniyosinositozlar",
        "Febril Konvulsiyonlar ve Epilepsi", "Çocuklarda baş ağrısı", "Nörokütan hastalıklar ve Hareket Bozuklukları",
        "Nöromuskuler Hastalıklar, PTC, Stroke", "Nörodejeneratif ve Demiyelizan Hastalıklar"],
    "Romatoloji": ["JIA", "Ankilozan Spondilit ve Spondiloartopatiler", "Sistemik Lupus Eritamatozus",
        "Juvenil Dermatomiyozit", "Skleroderma - Behçet Hastalığı - Sjögren Sendromu",
        "Periyodik Ateş Sendromu", "Kawasaki Hastalığı", "Henoch Schönlein Purpurası"],
    "Nefroloji": [ "Nefr1", "Nefr2", "Nefr3"],
    "immunology": [ "İmmüno1", "İmmüno2", "İmmüno3"],
    "Alerji": ["Alerji1", "Alerji2"],
    "Gastroentroloji": ["Gis Semptomları ve Özofagus Hast.", "Mide-Barsak Hast., İBH",
        "Malabsorbsiyon ve Karaciğer Hast.", "Soru Çözümleri"],
    "Solunum": ["Konu ve Soru Çözümü"],
    "Kardiyoloji": ["Anamnez & Fizik Muayene", "Radyoloji & EKG", "Asiyonatik KKH", "Siyanotik KKH", "Soru Çözümü"],
    "Vitaminler": ["Rikets", "Vitamin & Mineral", "Vitamin Sorular", "Anne Sütü & Tamamlayıcı Beslenme"],
    "AcilTip": ["Çocuk Acil, Yoğun Bakım, Zehirlenmeler", "Soru Çözümü"],
    "SosyalPediyatri": ["Sosyal Pediyatri & Adolesan"],
    "Dokuntu": ["Bağışıklama", "Döküntülü Hastalıklar"],
    "Büyüme": ["Büyüme, Gelişme & Malnutrisyon"]
};

export default childOptionsMap;